branch-defaults:
  main:
    environment: operabase-backend-mvp-env-1
environment-defaults:
  operabase-backend-mvp-env-1:
    branch: null
    repository: null
global:
  application_name: operabase-backend-mvp
  default_ec2_keyname: null
  default_platform: Node.js 22
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
